# Generated by Django 4.1.2 on 2022-10-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_song_date_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='Song_id',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Artiste_id',
            new_name='artiste_id',
        ),
    ]
